### ISSUE TITLE
[BUG]: BraintreePayPalButtons fail to render

### ISSUE THREAD

**Issue by 9nick9** [paypal/react-paypal-js#215] opened 2021-12-02 09:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

I am trying to use the BraintreePayPalButtons as follows:

```return (
    <div>
      <PayPalScriptProvider
        options={{
          'client-id': paypalToken,
          components: 'buttons',
          'data-client-token': braintreeToken,
          intent: 'tokenize',
          vault: true,
          currency: 'USD',
        }}
      >
        <BraintreePayPalButtons
          disabled={false}
          fundingSource="paypal" // Available values are: ["paypal", "card", "credit", "paylater", "venmo"]
          createBillingAgreement={createBillingAgreement}
          onApprove={onApprove}
        />
      </PayPalScriptProvider>
    </div>
  );
```

However, this fails to render. I can get around the issue by pulling in the braintree-web npm package and pointing window.braintree to this package.  I see react-paypal-js successfully downloading the braintree scripts but something isn't initializing this on the window properly.

### 😕 Current Behavior

Paypal button fails to render with the following error message:

Failed to load the PayPal JS SDK script. TypeError: Cannot read properties of undefined (reading 'client')
in BraintreePayPalButtons (created by PaypalCheckout)

### 🤔 Expected Behavior

Paypal button renders successfully.

### 🌍 Environment

```markdown
| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  |            |
| Browser          |            |
| Operating System |            |
```

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### ➕ Anything else?

This feels like a race condition causing the braintree script to be used before it is initialized but that is just a guess from my end.

**Comment by borodovisin** [comment] 2021-12-14 20:53
Hi @9nick9, sorry to take so long for a response. I was trying to replicate the exact same problem you're facing, unfortunately, I did not see the error message. You mention that `react-paypal-js` can successfully load the Braintree library.
That means you can see these two script loads in the Network tab: 
<img width="283" alt="Screen Shot 2021-12-14 at 3 51 05 PM" src="https://user-images.githubusercontent.com/26287838/146077380-f6fed167-4020-416f-a112-b5179e942196.png">

And when you try to access in the DevTool console to `window.braintree` it's `undefine`?
This is what you're facing now trying to use the Braintree?

**Comment by borodovisin** [comment] 2021-12-14 21:05
@9nick9 that happens all the time?. What browser are you using?. 

If you load this script in a mock HTML pate can you see `window.braintree`?

**Comment by 9nick9** [comment] 2021-12-15 09:25
I just tried 
```
<html><head></head>
<body>
    <script src="https://js.braintreegateway.com/web/3.79.1/js/client.min.js"></script>
    <div id=test>booo</div>
    <script>
        document.getElementById("test").innerHTML = window.braintree;
    </script>
</body>
</html>
```
and the window.braintree value is set as expected.

I am using chrome.

**Comment by borodovisin** [comment] 2021-12-15 22:21
Hi @9nick9, I tried to replicate the issue using the exact same code you post above.
But I'm not able to replicate that issue where the `window.braintree` is undefined. Please can you see if you're able to reproduce it on the [codesandbox](https://codesandbox.io/s/late-tdd-c237n?file=/src/App.js)

I don't see how the braintree `client.min.js`is load and the `window.braintree` is not set on the context.

Can you help me trying to get the same error on the codesandbox, or if you are doing something special with and iframe. Where are you using theses components in a NextJs app, or ReactJS app?

**Comment by borodovisin** [comment] 2021-12-20 23:03
Hi @9nick9, can you give us a little more information about what version of React are you using, the browser version, and the Operating System, please?

**Comment by 9nick9** [comment] 2021-12-21 09:30
React 16.9.0.  OSX Big Sur, Chrome 96.0.4664.110

**Comment by borodovisin** [comment] 2021-12-21 17:08
Hi @9nick9 are you able to recreate the issue? Can you share a code example?

**Comment by 9nick9** [comment] 2022-01-14 18:18
@borodovisin I was talking to a colleague about this and he looked at the script and saw that the issue seems to be caused due to using AMD loaders on my end. It appears as though the following section will cause that problem.
```
!(function (e) {
  var t;
  "object" == typeof exports && "undefined" != typeof module
    ? (module.exports = e())
    : "function" == typeof define && define.amd
    ? define([], e)
    : ((
        (t =
          "undefined" != typeof window
            ? window
            : "undefined" != typeof global
            ? global
            : "undefined" != typeof self
            ? self
            : this).braintree || (t.braintree = {})
      ).client = e());
```
Let me know if that helps.

**Comment by borodovisin** [comment] 2022-01-14 19:55
Hi @9nick9, that information is super useful.
Now I can see what is going on in the library. Thanks a lot for your patience and also for your help.

We'll start working on this issue probably next week. This is a good case we didn't have in mind during the library development. 🎯

**Comment by borodovisin** [comment] 2022-01-14 23:01
Hi @9nick9, can you provide how you are using the AMD. I mean you are loading directly from CDN the `requirejs` script and it's in the global scope. 

Can you give us a little more info/context on how you're using it? 🤔

**Comment by marcusdarmstrong** [comment] 2022-01-15 14:45
Hi, I’m the aforementioned colleague. We don’t actually use the AMD implementation on the page, it’s just present for some legacy stuff. The problem is simply that because it’s present, the UMD of the Braintree scripts declines to install Braintree onto `window`, and thus this lookup fails: https://github.com/paypal/react-paypal-js/blob/main/src/utils.ts#L23

**Comment by borodovisin** [comment] 2022-01-15 15:13
Hi @marcusdarmstrong, thanks for the details on this. Probably next week we can start working on this issue since we have enough information.

Thanks again for all the patience and the help finding this bug.

**Comment by borodovisin** [comment] 2022-01-17 22:12
Hi @9nick9 and @marcusdarmstrong, here you can track the [PR](https://github.com/paypal/react-paypal-js/pull/237) containing the bug fix.

**Comment by borodovisin** [comment] 2022-01-18 19:06
Hi @9nick9 and @marcusdarmstrong, here is some example with a workaround related to the issue you are facing now [repo](https://github.com/borodovisin/braintree-example).

The repo contains a description of what is going on on the `react-paypal-js`. 🧠 

Also you can create your custom `Braintree` wrapper component similar to the `BraintreePayPalButtons`and load the Braintree using a different approach. These are the options we can propose to solve this problem.

I truly hope this can be helpful for you 🙏 
Please feel free to leave any feedback/comments.

**Comment by marcusdarmstrong** [comment] 2022-01-18 19:23
We have no interest in _using_ AMD (and our legacy AMD implementation on the relevant pages wouldn't even support such usage)... We're certainly capable of creating a the window namespace via our own means (and we're currently doing so, by way of an npm dependency on braintree-web), but that has the downside that we're duplicately loading braintree on the page—once for our injection onto the namespace, and then the script injection occuring via react-paypal-js.

I'd argue that it doesn't make sense to be injecting a UMD module onto the page if your accessor code doesn't intend to support UMDs... But that said, a much better solution, IMO, would be to either: 1. use an NPM dependency instead of loading UMDs at runtime or 2. allow us to provide our own copy of braintree via props and short circuit the attempted UMD load.

**Comment by borodovisin** [comment] 2022-02-02 16:16
Hi @9nick9 and @marcusdarmstrong the new release `7.6` has the changes related to handling manually the Braintree instance. Please we encourage you to update the dependency and send us any feedback or close the issue if the problem was solved.

Thanks for your patience and help on this 🙏

**Comment by 9nick9** [comment] 2022-02-02 16:50
Thanks @borodovisin . We updated our code to use this today and it's looking good so far.

**Comment by borodovisin** [comment] 2022-02-02 18:33
Hi @9nick9, awesome, I'm going to close this issue.

**Closed by borodovisin** 2022-02-02 18:33 UTC
