### ISSUE TITLE
[BUG]: Paypal Button Click opens auto:blank#blocked popup

### ISSUE THREAD

**Issue by praveencloudalgo** [paypal/react-paypal-js#370] opened 2023-07-21 14:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### 🐞 Describe the Bug

We have implemented Paypal integration in our web code. But there is a very weird issue coming, whenever we click on the button of Paypal it opens auto:blank#blocked popup on top of Paypal popup. See the screenshot attached. Once we close this blocked popup than we see the Paypal popup to proceed with the payment.

![Screenshot 2023-07-21 at 6 22 20 PM](https://github.com/paypal/react-paypal-js/assets/129676978/a1894fed-9631-457d-a051-916f9faab80b)
![Screenshot 2023-07-21 at 6 23 11 PM](https://github.com/paypal/react-paypal-js/assets/129676978/fe6bdac0-1375-4cd9-b869-bd7d460d9161)

### 😕 Current Behavior

This is the code that is implemented

import { PayPalScriptProvider, PayPalButtons } from "@paypal/react-paypal-js";
<PayPalScriptProvider
                            options={{
                              clientId:
                                process.env.NEXT_PUBLIC_PAYPAL_CLIENT_ID,
                              debug: true,
                              currency: "USD",
                              intent: "capture",
                            }}
                          >
                            <PayPalButtons
                              style={{
                                layout: "horizontal",
                                color: "blue",
                                shape: "pill",
                                height: 40,
                                tagline: false,
                                label: "pay",
                              }}
                              onClick={async (data, actions) => {
                                const formErrors =
                                  await formikProps.validateForm();

                                formikProps.setTouched({
                                  ...formikProps.touched,
                                  ...formikProps.errors,
                                });
                                if (JSON.stringify(formErrors) !== "{}") {
                                  return false;
                                }
                              }}
                              createOrder={async (data, actions) => {
                                return await createPaypalOrder(
                                  formikProps.values,
                                );
                              }}
                              onApprove={paypalBuyAcknowledgement}
                            />
                          </PayPalScriptProvider> 
                          
                          
                          ![Screenshot 2023-07-21 at 6 22 20 PM](https://github.com/paypal/react-paypal-js/assets/129676978/a1894fed-9631-457d-a051-916f9faab80b)
![Screenshot 2023-07-21 at 6 23 11 PM](https://github.com/paypal/react-paypal-js/assets/129676978/fe6bdac0-1375-4cd9-b869-bd7d460d9161)

### 🤔 Expected Behavior

As per the documentation, user should see this type of behaviour but see some other behaviour

![Screenshot 2023-07-21 at 6 27 40 PM](https://github.com/paypal/react-paypal-js/assets/129676978/dd6e8b7e-77ff-4759-8e22-88cc8ac41d4d)
,

### 🔬 Minimal Reproduction

```markdown
Please let us know if you need specific url and credential to test
```

### 🌍 Environment

```markdown
| Software         | Version(s) |
| ---------------- | ---------- |
| react-paypal-js  |  8.1.0     |
| Browser          |Chrome, Edge|
| Operating System | Mac OS Ventura3.4.1 (c)        |
```

### Relevant log output

```shell
NA
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### ➕ Anything else?

NA

**Comment by xenotime-india** [comment] 2023-08-03 18:57
The issue might be related to "Cross-Origin-Opener-Policy". Could you check the console warning related to the Paypal domain?

**Comment by hemengke1997** [comment] 2023-08-08 06:22
Same issue. Only got this in console:
<img width="1433" alt="image" src="https://github.com/paypal/react-paypal-js/assets/49073282/89a5be55-8221-4b5e-8b09-8e15934b8ae5">

**Comment by gregjopa** [comment] 2023-08-08 20:16
Hi @praveencloudalgo, please share a reproduction url. My initial thought is along the same lines as @xenotime-india where there it may be related to using `"Cross-Origin-Opener-Policy"`

**Comment by devchristina** [comment] 2023-09-13 17:04
@praveencloudalgo Since we haven't had a response to more information, I'm going to close this issue without action. If you are still facing this issue, please re-open and provide the information requested.

**Closed by devchristina** 2023-09-13 17:04 UTC

**Comment by jericopulvera** [comment] 2023-12-25 08:03
> Hi @praveencloudalgo, please share a reproduction url. My initial thought is along the same lines as @xenotime-india where there it may be related to using `"Cross-Origin-Opener-Policy"`

what's the fix if it's related to this? or it's just not possible on paypal sdk at all?
